### ISSUE TITLE
Python SDK needs change to reflect new Sia Skynet upload endpoint

### ISSUE THREAD

**Issue by jjchauhan** [NebulousLabs/python-skynet#1]
Current value: 
 'https://siasky.net/',
  'portalUploadPath' : '/api/skyfile',
  'portalFileFieldname' : 'file',
  'customFilename':

Expected value:
 'https://siasky.net/',
  'portalUploadPath' : '/skynet/skyfile/',
  'portalFileFieldname' : 'file',
  'customFilename':

**Comment by peterjanbrone** [comment]
Hi @jjchauhan does this commit cover your requested changes?
https://github.com/NebulousLabs/python-skynet/commit/84b76925a0a48626a1ca1c557c01a9aed1d4e485

The python Skynet package on PyPI, which is at version 0.0.5 since Monday had these changes already. It seems I forget to commit and push to master, however. Wasn't expecting people to copy-paste from the repo.

**Comment by jjchauhan** [comment]
Tested with latest siaskynet python package and it worked fine. Thanks PJ
